import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h3  className={styles.title}>
        Safety First: Sicherheit ist entscheidender Faktor bei Reisen
        </h3>
        <p  className={styles.p1}>
          In der heutigen Zeit gewinnt der Sicherheitsgedanke immer mehr an Wichtigkeit. Bei der Planung einer Workation suchen Reisende dementsprechend nicht nur nach inspirierenden Orten für ihre berufliche Tätigkeit, sondern legen auch großen Wert auf <strong> Sicherheit, gesellschaftliche Akzeptanz und allgemeines Wohlbefinden am Zielort</strong>. In diesem Kontext spielen der Global Peace Index, der Acceptance Index und der World Happiness Report eine zentrale Rolle.
        </p>
        <p className={styles.description} >
          Nach dem <strong> Global Peace-Index</strong> gelten Länder mit niedrigen Werten wie Malta (1,231), Dänemark (1,310) und Irland (1,312) als besonders sicher und friedlich. Deutschland befindet sich mit einem Wert von 1,456 ebenfalls in den Top 20. Neben der Sicherheit ist die gesellschaftliche Akzeptanz ein weiterer wichtiger Faktor für viele Workation-Reisende. Der Acceptance Index bewertet, wie offen die Gesellschaft in verschiedenen Ländern ist. Besonders die Niederlande (9,46), Norwegen (9,39), Schweden (9,18), Kanada (9,02) und Spanien (8,77) sind hier zu nennen
        </p>
        <p>
          Deutschland erreicht im <strong>World-Happiness-Index</strong> einen Score von 6,892, was auf ein relativ hohes Maß an Lebenszufriedenheit hindeutet. Länder wie Finnland, Dänemark und Norwegen, die hohe Werte von über 7,5 aufweisen, können als besonders attraktive Workation-Ziele für diejenigen gelten, die Wert auf ein glückliches und in der Gesamtheit ausgeglichenes Umfeld legen.
        </p>
        <Image
              className={styles.logo}
              src="/wohnen-arbeiten-laender.jpg"
              alt="photo"
              width={1084}
              height={500}
            />
      </main>
    </>
  );
}
